import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Logitech Actions SDK
  actionsSdkSidebar: [{type: 'autogenerated', dirName: 'actions-sdk'}],
  
  // Download Wheel SDK for Windows
  wheelDownloadSidebar: [{type: 'autogenerated', dirName: 'wheel-download'}],
  
  // LightSync SDK
  steeringWheelSidebar: [{type: 'autogenerated', dirName: 'steering-wheel'}],
  
  // TrueForce SDK
  gamePanelSidebar: [{type: 'autogenerated', dirName: 'gamepanel'}],
  
  // Haptics G
  ledIlluminationSidebar: [{type: 'autogenerated', dirName: 'led-illumination'}],
  
  // Video SDK
  videoSdkSidebar: [{type: 'autogenerated', dirName: 'video-sdk'}],
  
  // Blue Voice SDK
  blueVoiceSdkSidebar: [{type: 'autogenerated', dirName: 'blue-voice-sdk'}],
};

export default sidebars;
